DuDoan/urls.py
from django.urls import path

from . import views

app_name = 'DuDoan'
urlpatterns = [
    path('', views.index, name='index'),
    path('ketqua', views.ketqua, name="ketqua")
]

DuDoanGiaDat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('DuDoan.urls', 'DuDoan'), namespace="DuDoan")),
    path('admin/', admin.site.urls),
]

DuDoan/models.py
from django.db import models

# Create your models here.

DuDoan/views.py
import email
import os

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from tensorflow.python.keras.models import load_model
from sklearn.preprocessing import RobustScaler
import numpy as np
import math
from sklearn import preprocessing
import pandas as pd
import locale

le = preprocessing.LabelEncoder()


# Create your views here.
def index(request):
    return render(request, 'dudoan.html', {})


@require_POST
def ketqua(request):
    model = load_model('model.h5')
    road = request.POST['road']
    type = request.POST['type']
    width = request.POST['width']
    length = request.POST['length']
    area = request.POST['area']
    bedroom = request.POST['bedroom']
    floor = request.POST['floor']
    direct = request.POST['direct']
    paper = request.POST['paper']
    district = request.POST['district']
    print(road, type, width, length, area, bedroom, floor, direct)
    newRc = {
        'Type Of Estate': type,
        'Legal': paper,
        'Square': area,
        'Width': width,
        'Length': length,
        'Floors': floor,
        'Bedrooms': bedroom,
        'Direction': direct,
        'Road': road,
    }
    df = pd.read_csv('dataclean.csv')
    df = df[['Type Of Estate','Legal','Square','Width','Length','Floors','Bedrooms','Direction','Road']]
    df = fixOutlier(df)
    df = df.append(newRc, ignore_index=True)
    df = ChuanHoa(df)
    df['Type Of Estate'] = le.fit_transform(df['Type Of Estate'])
    df['Direction'] = le.fit_transform(df['Direction'])
    df['Legal'] = le.fit_transform(df['Legal'])
    last = df[-1:]
    last['District_Huyện Hòa Vang'] = int(0)
    last['District_Quận Cẩm Lệ'] = int(0)
    last['District_Quận Hải Châu'] = int(0)
    last['District_Quận Liên Chiểu'] = int(0)
    last['District_Quận Ngũ Hành Sơn'] = int(0)
    last['District_Quận Sơn Trà'] = int(0)
    last['District_Quận Thanh Khê'] = int(0)
    match district:
        case 'Huyện Hòa Vang': last['District_Huyện Hòa Vang'] = int(1)
        case 'Quận Cẩm Lệ': last['District_Quận Cẩm Lệ'] = int(1)
        case 'Quận Hải Châu': last['District_Quận Hải Châu'] = int(1)
        case 'Quận Liên Chiểu': last['District_Quận Liên Chiểu'] = int(1)
        case 'Quận Ngũ Hành Sơn': last['District_Quận Ngũ Hành Sơn'] = int(1)
        case 'Quận Sơn Trà': last['Quận Sơn Trà'] = int(1)
        case 'Quận Thanh Khê': last['District_Quận Thanh Khê'] = int(1)
    predicted = model.predict(last)
    locale.setlocale(locale.LC_ALL, 'vi_VN.UTF-8')
    predicted = np.expm1(predicted[0])
    return render(request, 'ketqua.html', {'price': locale.currency(float((predicted[0])), grouping=True)})


def fixOutlier(train_df):
    index = []
    for i in range(train_df.shape[0]):
        if i == 0:
            continue
        if train_df['Square'].iloc[i] >= 450:
            if i not in index:
                index.append(i)
        elif train_df['Length'].iloc[i] > 60:
            if i not in index:
                index.append(i)
        elif train_df['Width'].iloc[i] > 50:
            if i not in index:
                index.append(i)
        elif train_df['Floors'].iloc[i] > 18:
            if i not in index:
                index.append(i)
        elif train_df['Road'].iloc[i] > 100:
            if i not in index:
                index.append(i)
        elif train_df['Bedrooms'].iloc[i] > 40:
            if i not in index:
                index.append(i)
    train_df = train_df.drop(index)
    return train_df


def ChuanHoa(train_df):
    scaler = RobustScaler()
    num_cols = ['Road','Square','Width','Length','Floors','Bedrooms']
    train_df[num_cols] = scaler.fit_transform(train_df[num_cols])
    return train_df

templates/dudoan.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>DuDoanGiaDat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"
        integrity="sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/css/bootstrap-select.min.css"
        integrity="sha512-mR/b5Y7FRsKqrYZou7uysnOdCIJib/7r5QeJMFvLNHNhtye3xJp1TdJVPLtetkukFn227nKpXD9OjUc09lx97Q=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Include Twitter Bootstrap and jQuery: -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css" />
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700;900&display=swap');

        *,
        body {
            font-family: 'Poppins', sans-serif;
            font-weight: 400;
            -webkit-font-smoothing: antialiased;
            text-rendering: optimizeLegibility;
            -moz-osx-font-smoothing: grayscale;
        }

        html,
        body {
            height: 100%;
            background-color: #152733;
        }

        input[type='number'] {
            appearance: none;
        }

        input::-webkit-inner-spin-button,
        input::-webkit-outer-spin-button {
            appearance: none;
            -webkit-appearance: none;
        }

        .form-holder {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            min-height: 100vh;
        }

        .form-holder .form-content {
            position: relative;
            text-align: center;
            display: -webkit-box;
            display: -moz-box;
            display: -ms-flexbox;
            display: -webkit-flex;
            display: flex;
            -webkit-justify-content: center;
            justify-content: center;
            -webkit-align-items: center;
            align-items: center;
            padding: 60px;
        }

        .form-content .form-items {
            border: 3px solid #fff;
            padding: 40px;
            display: inline-block;
            width: 100%;
            min-width: 540px;
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
            text-align: left;
            -webkit-transition: all 0.4s ease;
            transition: all 0.4s ease;
        }

        .form-content h3 {
            color: #fff;
            text-align: left;
            font-size: 28px;
            font-weight: 600;
            margin-bottom: 5px;
        }

        .form-content h3.form-title {
            margin-bottom: 30px;
        }

        .form-content p {
            color: #fff;
            text-align: left;
            font-size: 17px;
            font-weight: 300;
            line-height: 20px;
            margin-bottom: 30px;
        }


        .form-content label,
        .was-validated .form-check-input:invalid~.form-check-label,
        .was-validated .form-check-input:valid~.form-check-label {
            color: #fff;
        }

        .form-content input,
        .form-content select {
            width: 100%;
            padding: 9px 20px;
            text-align: left;
            border: 0;
            outline: 0;
            border-radius: 6px;
            background-color: #fff;
            font-size: 15px;
            font-weight: 300;
            color: #000;
            -webkit-transition: all 0.3s ease;
            transition: all 0.3s ease;
            margin-bottom: 16px;
        }


        .btn-primary {
            background-color: #6C757D;
            outline: none;
            border: 0px;
            box-shadow: none;
        }

        .btn-primary:hover,
        .btn-primary:focus,
        .btn-primary:active {
            background-color: #495056;
            outline: none !important;
            border: none !important;
            box-shadow: none;
        }

        .form-content textarea {
            position: static !important;
            width: 100%;
            padding: 8px 20px;
            border-radius: 6px;
            text-align: left;
            background-color: #fff;
            border: 0;
            font-size: 15px;
            font-weight: 300;
            color: #000;
            outline: none;
            resize: none;
            height: 120px;
            -webkit-transition: none;
            transition: none;
            margin-bottom: 14px;
        }

        .form-content textarea:hover,
        .form-content textarea:focus {
            border: 0;
            background-color: #ebeff8;
            color: #000;
        }

        .form-button {
            display: flex;
            justify-content: center;
        }

        .mv-up {
            margin-top: -9px !important;
            margin-bottom: 8px !important;
        }

        .invalid-feedback {
            color: #ff606e;
        }

        .valid-feedback {
            color: #2acc80;
        }
    </style>
</head>

<body>
    <div class="form-body">
        <!-- <div class="row"> -->
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>Dự đoán giá nhà đất tại TP. Đà Nẵng</h3>
                    <p>Nhập thông tin nhà đất vào form dưới đây.</p>
                    <form class="requires-validation" method="post" action="{% url 'DuDoan:ketqua' %}" novalidate>
                        {% csrf_token %}
                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="road">Độ rộng đường: </label>
                            <input class="form-control" type="number" name="road" placeholder="Động rộng đường"
                                required>
                        </div>

                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="type">Loại bất động sản: </label>
                            <select class="form-select" name="type" required>
                                <option selected value="Nhà trong hẻm">Nhà trong hẻm</option>
                                <option value="Đất thổ cư, đất ở">Đất thổ cư, đất ở</option>
                                <option value="Nhà mặt tiền">Nhà mặt tiền</option>
                                <option value="Đất nền, liền kề, đất dự án">Đất nền, liền kề, đất dự án</option>
                                <option value="Nhà hàng, khách sạn">Nhà hàng, khách sạn</option>
                                <option value="Biệt thự, nhà liền kề">Biệt thự, nhà liền kề</option>
                                <option value="Căn hộ chung cư">Căn hộ chung cư</option>
                                <option value="Mặt bằng">Mặt bằng</option>
                                <option value="Phòng trọ, nhà trọ">Phòng trọ, nhà trọ</option>
                                <option value="Shop, kiot, quán">Shop, kiot, quán</option>
                            </select>
                        </div>

                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="length">Chiều dài: </label>
                            <input class="form-control" type="number" name="length" placeholder="Chiều dài" required>
                        </div>

                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="width">Chiều rộng: </label>
                            <input class="form-control" type="number" name="width" placeholder="Chiều rộng" required>
                        </div>

                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="area">Diện tích sử dụng: </label>
                            <input class="form-control" type="number" name="area" placeholder="Diện tích sử dụng"
                                required>
                        </div>

                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="bedroom">Số lượng phòng ngủ: </label>
                            <input class="form-control" type="number" name="bedroom" placeholder="Số lượng phòng ngủ"
                                required>
                        </div>

                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="floor">Số tầng: </label>
                            <input class="form-control" type="number" name="floor" placeholder="Số tầng" required>
                        </div>

                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="direct">Hướng: </label>
                            <select class="form-select" name="direct" required>
                                <option selected value="Nam">Nam</option>
                                <option value="Bắc">Bắc</option>
                                <option value="Tây">Tây</option>
                                <option value="Đông">Đông</option>
                                <option value="Tây Nam">Tây Nam</option>
                                <option value="Tây Bắc">Tây Bắc</option>
                                <option value="Đông Nam">Đông Nam</option>
                                <option value="Đông Bắc">Đông Bắc</option>
                            </select>
                        </div>

                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="district">Quận: </label>
                            <select class="form-select" name="district" required>
                                <option selected value="Huyện Hòa Vang">Huyện Hòa Vang</option>
                                <option value="Quận Cẩm Lệ">Quận Cẩm Lệ</option>
                                <option value="Quận Hải Châu">Quận Hải Châu</option>
                                <option value="Quận Liên Chiểu">Quận Liên Chiểu</option>
                                <option value="Quận Ngũ Hành Sơn">Quận Ngũ Hành Sơn</option>
                                <option value="Quận Sơn Trà">Quận Sơn Trà</option>
                                <option value="Quận Thanh Khê">Quận Thanh Khê</option>
                            </select>
                        </div>

                        <div class="col-md-12">
                            <label class="mb-2 mr-1" for="paper">Giấy tờ: </label>
                            <select class="form-select" name="paper" required>
                                <option selected value="Sổ hồng/ Sổ đỏ">Sổ hồng/ Sổ đỏ</option>
                                <option value="Giấy tờ hợp lệ">Giấy tờ hợp lệ</option>
                            </select>
                        </div>

                        <div class="form-button mt-3">
                            <button id="submit" type="submit" class="btn btn-primary">Dự đoán</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- </div> -->
    </div>

</body>

</html>

templates/ketqua.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kết quả</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"
            integrity="sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/css/bootstrap-select.min.css" integrity="sha512-mR/b5Y7FRsKqrYZou7uysnOdCIJib/7r5QeJMFvLNHNhtye3xJp1TdJVPLtetkukFn227nKpXD9OjUc09lx97Q==" crossorigin="anonymous"
  referrerpolicy="no-referrer" />
    <!-- Include Twitter Bootstrap and jQuery: -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css"/>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700;900&display=swap');

        *, body {
            font-family: 'Poppins', sans-serif;
            font-weight: 400;
            -webkit-font-smoothing: antialiased;
            text-rendering: optimizeLegibility;
            -moz-osx-font-smoothing: grayscale;
        }

        html, body {
            height: 100%;
            background-color: #152733;
            overflow: hidden;
        }

        .form-holder {
              display: flex;
              flex-direction: column;
              justify-content: center;
              align-items: center;
              text-align: center;
              min-height: 100vh;
        }

        .form-holder .form-content {
            position: relative;
            text-align: center;
            display: -webkit-box;
            display: -moz-box;
            display: -ms-flexbox;
            display: -webkit-flex;
            display: flex;
            -webkit-justify-content: center;
            justify-content: center;
            -webkit-align-items: center;
            align-items: center;
            padding: 60px;
        }

        .form-content .form-items {
            border: 3px solid #fff;
            padding: 40px;
            display: inline-block;
            width: 100%;
            min-width: 540px;
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
            text-align: left;
            -webkit-transition: all 0.4s ease;
            transition: all 0.4s ease;
        }

        .form-content h3 {
            color: #fff;
            text-align: left;
            font-size: 28px;
            font-weight: 600;
            margin-bottom: 5px;
        }

        .form-content h3.form-title {
            margin-bottom: 30px;
        }

        .form-content p {
            color: #fff;
            text-align: left;
            font-size: 17px;
            font-weight: 300;
            line-height: 20px;
            margin-bottom: 30px;
        }


        .form-content label, .was-validated .form-check-input:invalid~.form-check-label, .was-validated .form-check-input:valid~.form-check-label{
            color: #fff;
        }

        .form-content input[type=text], .form-content input[type=password], .form-content input[type=email], .form-content select {
            width: 100%;
            padding: 9px 20px;
            text-align: left;
            border: 0;
            outline: 0;
            border-radius: 6px;
            background-color: #fff;
            font-size: 15px;
            font-weight: 300;
            color: #000;
            -webkit-transition: all 0.3s ease;
            transition: all 0.3s ease;
            margin-top: 16px;
        }


        .btn-primary{
            background-color: #6C757D;
            outline: none;
            border: 0px;
             box-shadow: none;
        }

        .btn-primary:hover, .btn-primary:focus, .btn-primary:active{
            background-color: #495056;
            outline: none !important;
            border: none !important;
             box-shadow: none;
        }

        .form-content textarea {
            position: static !important;
            width: 100%;
            padding: 8px 20px;
            border-radius: 6px;
            text-align: left;
            background-color: #fff;
            border: 0;
            font-size: 15px;
            font-weight: 300;
            color: #000;
            outline: none;
            resize: none;
            height: 120px;
            -webkit-transition: none;
            transition: none;
            margin-bottom: 14px;
        }

        .form-content textarea:hover, .form-content textarea:focus {
            border: 0;
            background-color: #ebeff8;
            color: #000;
        }
    </style>
</head>

<body>
    <div class="form-holder">
        <form class="form-content">
            <div class="form-group">
                <label class="col-lg-12 control-label">Giá mảnh đất của bạn là:</label>
                <div>
                    <input class="form-control" type="text" value="{{ price }}">
                </div>
            </div>
        </form>
    </div>
</body>
</html>